import type { Task } from "./types";

export const mockTasks: Task[] = [
  {
    task_id: "TASK-001",
    title: "Build landing page",
    description:
      "Create a responsive landing page with hero section, feature grid, and CTA components following the design system.",
    current_status: "completed",
    objective_summary: "Deliver a production-ready landing page",
    origin: {
      source_system: "linear",
      source_type: "ingress_request",
      source_id: "LIN-2847",
      ingress_id: "openclaw-001",
      ingress_name: "OpenClaw",
    },
    relationships: {
      parent_task_id: null,
      child_task_ids: ["TASK-001a", "TASK-001b"],
      dependencies: [],
    },
    assigned_executor: {
      executor_type: "codex",
      executor_id: "codex-instance-alpha",
      assignment_reason: "Frontend capability match",
    },
    evidence_summary: {
      artifact_count: 3,
      artifact_type_counts: { pull_request: 1, commit: 2 },
      verification_status_counts: { verified: 3 },
      validated_artifact_count: 3,
      completion_evidence: {
        policy: "artifact_backed",
        status: "validated",
        required_artifact_types: ["pull_request"],
        validated_artifact_ids: ["art-001", "art-002", "art-003"],
        validation_method: "automated",
        validated_at: "2024-01-15T14:32:00Z",
      },
    },
    verification_summary: {
      result: "accepted",
      completion_accepted: true,
      evidence_sufficient: true,
      reasons: ["PR merged with passing CI", "All acceptance criteria met"],
      evaluated_at: "2024-01-15T14:32:00Z",
    },
    reconciliation_summary: {
      result: "no_mismatch",
      linear_state: "done",
      github_state: "merged",
      harness_state: "completed",
      mismatches: [],
      evaluated_at: "2024-01-15T14:35:00Z",
    },
    review_summary: {
      status: "none",
      request_count: 0,
      decision_count: 0,
      latest_request: null,
      latest_decision: null,
      requests: [],
      decisions: [],
    },
    evaluation_summary: {
      count: 1,
      latest_action: "transition_applied",
      latest_recorded_at: "2024-01-15T14:32:00Z",
      latest_target_status: "completed",
    },
    timestamps: {
      created_at: "2024-01-14T09:00:00Z",
      updated_at: "2024-01-15T14:35:00Z",
      completed_at: "2024-01-15T14:32:00Z",
    },
    timeline: [
      {
        event_id: "TASK-001:created",
        event_type: "task_created",
        occurred_at: "2024-01-14T09:00:00Z",
        summary: "Task created",
        source: "linear",
        details: { status: "intake_ready" },
      },
      {
        event_id: "TASK-001:status:1",
        event_type: "status_transition",
        occurred_at: "2024-01-14T09:15:00Z",
        summary: "Status changed intake_ready -> assigned",
        source: "harness",
        details: { from_status: "intake_ready", to_status: "assigned" },
      },
      {
        event_id: "TASK-001:artifact:art-001",
        event_type: "artifact_captured",
        occurred_at: "2024-01-15T10:20:00Z",
        summary: "Artifact captured: pull_request",
        source: "github",
        details: { type: "pull_request", pull_request_number: 142 },
      },
      {
        event_id: "TASK-001:eval:1",
        event_type: "evaluation_recorded",
        occurred_at: "2024-01-15T14:32:00Z",
        summary: "Evaluation recorded: accept_completion",
        source: "harness",
        details: { action: "accept_completion", accepted_completion: true },
      },
      {
        event_id: "TASK-001:status:2",
        event_type: "status_transition",
        occurred_at: "2024-01-15T14:32:00Z",
        summary: "Status changed executing -> completed",
        source: "harness",
        details: { from_status: "executing", to_status: "completed" },
      },
    ],
    priority: "high",
  },
  {
    task_id: "TASK-002",
    title: "Implement auth flow",
    description:
      "Set up OAuth2 authentication with GitHub provider, session management, and protected route middleware.",
    current_status: "blocked",
    objective_summary: "Working authentication system with GitHub OAuth",
    origin: {
      source_system: "linear",
      source_type: "ingress_request",
      source_id: "LIN-2851",
      ingress_id: "openclaw-001",
      ingress_name: "OpenClaw",
    },
    relationships: {
      parent_task_id: null,
      child_task_ids: [],
      dependencies: [{ task_id: "TASK-001", dependency_type: "blocks" }],
    },
    assigned_executor: {
      executor_type: "codex",
      executor_id: "codex-instance-beta",
      assignment_reason: "Backend capability match",
    },
    evidence_summary: {
      artifact_count: 1,
      artifact_type_counts: { commit: 1 },
      verification_status_counts: { unverified: 1 },
      validated_artifact_count: 0,
      completion_evidence: {
        policy: "artifact_backed",
        status: "insufficient",
        required_artifact_types: ["pull_request"],
        validated_artifact_ids: [],
        validation_method: null,
        validated_at: null,
      },
    },
    verification_summary: {
      result: "insufficient_evidence",
      completion_accepted: false,
      evidence_sufficient: false,
      reasons: [
        "No PR found for claimed completion",
        "Commit exists but not linked to PR",
      ],
      evaluated_at: "2024-01-16T11:45:00Z",
    },
    reconciliation_summary: {
      result: "contradictory_facts",
      linear_state: "in_progress",
      github_state: "no_pr",
      harness_state: "blocked",
      mismatches: ["Linear shows in_progress but work is blocked"],
      evaluated_at: "2024-01-16T11:50:00Z",
    },
    review_summary: {
      status: "requested",
      request_count: 1,
      decision_count: 0,
      latest_request: {
        review_request_id: "rev-req-001",
        reason: "Insufficient evidence for completion claim",
        requested_by: "harness",
        requested_at: "2024-01-16T11:45:00Z",
      },
      latest_decision: null,
      requests: [
        {
          review_request_id: "rev-req-001",
          reason: "Insufficient evidence for completion claim",
          requested_by: "harness",
          requested_at: "2024-01-16T11:45:00Z",
        },
      ],
      decisions: [],
    },
    evaluation_summary: {
      count: 1,
      latest_action: "transition_applied",
      latest_recorded_at: "2024-01-16T11:45:00Z",
      latest_target_status: "blocked",
    },
    timestamps: {
      created_at: "2024-01-15T10:00:00Z",
      updated_at: "2024-01-16T11:50:00Z",
      completed_at: null,
    },
    timeline: [
      {
        event_id: "TASK-002:created",
        event_type: "task_created",
        occurred_at: "2024-01-15T10:00:00Z",
        summary: "Task created",
        source: "linear",
        details: { status: "intake_ready" },
      },
      {
        event_id: "TASK-002:status:1",
        event_type: "status_transition",
        occurred_at: "2024-01-15T10:30:00Z",
        summary: "Status changed intake_ready -> assigned",
        source: "harness",
        details: { from_status: "intake_ready", to_status: "assigned" },
      },
      {
        event_id: "TASK-002:artifact:art-010",
        event_type: "artifact_captured",
        occurred_at: "2024-01-16T09:00:00Z",
        summary: "Artifact captured: commit",
        source: "github",
        details: { type: "commit", commit_sha: "a1b2c3d" },
      },
      {
        event_id: "TASK-002:eval:1",
        event_type: "evaluation_recorded",
        occurred_at: "2024-01-16T11:45:00Z",
        summary: "Evaluation recorded: block_completion",
        source: "harness",
        details: {
          action: "block_completion",
          requires_review: true,
          reasons: ["Insufficient evidence"],
        },
      },
      {
        event_id: "TASK-002:review:rev-req-001",
        event_type: "review_requested",
        occurred_at: "2024-01-16T11:45:00Z",
        summary: "Manual review requested",
        source: "harness",
        details: { reason: "Insufficient evidence for completion claim" },
      },
      {
        event_id: "TASK-002:status:2",
        event_type: "status_transition",
        occurred_at: "2024-01-16T11:45:00Z",
        summary: "Status changed executing -> blocked",
        source: "harness",
        details: { from_status: "executing", to_status: "blocked" },
      },
    ],
    priority: "critical",
  },
  {
    task_id: "TASK-003",
    title: "Deploy onboarding backend",
    description:
      "Deploy the user onboarding service to production with proper environment configuration and monitoring.",
    current_status: "executing",
    objective_summary: "Production deployment of onboarding service",
    origin: {
      source_system: "linear",
      source_type: "ingress_request",
      source_id: "LIN-2855",
      ingress_id: "openclaw-002",
      ingress_name: "OpenClaw",
    },
    relationships: {
      parent_task_id: null,
      child_task_ids: [],
      dependencies: [{ task_id: "TASK-002", dependency_type: "blocks" }],
    },
    assigned_executor: {
      executor_type: "codex",
      executor_id: "codex-instance-gamma",
      assignment_reason: "DevOps capability match",
    },
    evidence_summary: {
      artifact_count: 2,
      artifact_type_counts: { pull_request: 1, log: 1 },
      verification_status_counts: { verified: 1, unverified: 1 },
      validated_artifact_count: 1,
      completion_evidence: {
        policy: "artifact_backed",
        status: "pending",
        required_artifact_types: ["pull_request", "log"],
        validated_artifact_ids: ["art-020"],
        validation_method: null,
        validated_at: null,
      },
    },
    verification_summary: {
      result: "pending",
      completion_accepted: false,
      evidence_sufficient: false,
      reasons: ["Awaiting deployment confirmation"],
      evaluated_at: "2024-01-17T08:00:00Z",
    },
    reconciliation_summary: {
      result: "pending",
      linear_state: "in_progress",
      github_state: "pr_open",
      harness_state: "executing",
      mismatches: [],
      evaluated_at: "2024-01-17T08:00:00Z",
    },
    review_summary: {
      status: "none",
      request_count: 0,
      decision_count: 0,
      latest_request: null,
      latest_decision: null,
      requests: [],
      decisions: [],
    },
    evaluation_summary: {
      count: 1,
      latest_action: "no_op",
      latest_recorded_at: "2024-01-17T08:00:00Z",
      latest_target_status: null,
    },
    timestamps: {
      created_at: "2024-01-16T14:00:00Z",
      updated_at: "2024-01-17T08:00:00Z",
      completed_at: null,
    },
    timeline: [
      {
        event_id: "TASK-003:created",
        event_type: "task_created",
        occurred_at: "2024-01-16T14:00:00Z",
        summary: "Task created",
        source: "linear",
        details: { status: "intake_ready" },
      },
      {
        event_id: "TASK-003:status:1",
        event_type: "status_transition",
        occurred_at: "2024-01-16T14:30:00Z",
        summary: "Status changed intake_ready -> assigned",
        source: "harness",
        details: { from_status: "intake_ready", to_status: "assigned" },
      },
      {
        event_id: "TASK-003:status:2",
        event_type: "status_transition",
        occurred_at: "2024-01-16T15:00:00Z",
        summary: "Status changed assigned -> executing",
        source: "harness",
        details: { from_status: "assigned", to_status: "executing" },
      },
      {
        event_id: "TASK-003:artifact:art-020",
        event_type: "artifact_captured",
        occurred_at: "2024-01-17T07:30:00Z",
        summary: "Artifact captured: pull_request",
        source: "github",
        details: { type: "pull_request", pull_request_number: 156 },
      },
    ],
    priority: "high",
  },
  {
    task_id: "TASK-004",
    title: "Generate PRD-derived work items",
    description:
      "Decompose the product requirements document into structured work items with dependencies.",
    current_status: "failed",
    objective_summary: "Structured task breakdown from PRD",
    origin: {
      source_system: "manual",
      source_type: "manual",
      source_id: "manual-entry-001",
      ingress_id: null,
      ingress_name: null,
    },
    relationships: {
      parent_task_id: null,
      child_task_ids: ["TASK-004a", "TASK-004b", "TASK-004c"],
      dependencies: [],
    },
    assigned_executor: {
      executor_type: "claude",
      executor_id: "claude-instance-001",
      assignment_reason: "Planning capability match",
    },
    evidence_summary: {
      artifact_count: 0,
      artifact_type_counts: {},
      verification_status_counts: {},
      validated_artifact_count: 0,
      completion_evidence: {
        policy: "artifact_backed",
        status: "missing",
        required_artifact_types: ["output"],
        validated_artifact_ids: [],
        validation_method: null,
        validated_at: null,
      },
    },
    verification_summary: {
      result: "rejected",
      completion_accepted: false,
      evidence_sufficient: false,
      reasons: ["Executor failed with timeout", "No output artifacts generated"],
      evaluated_at: "2024-01-17T10:30:00Z",
    },
    reconciliation_summary: {
      result: "wrong_target",
      linear_state: "done",
      github_state: "no_activity",
      harness_state: "failed",
      mismatches: [
        "Linear marked done but no evidence in GitHub",
        "Harness detected failure state",
      ],
      evaluated_at: "2024-01-17T10:35:00Z",
    },
    review_summary: {
      status: "resolved",
      request_count: 1,
      decision_count: 1,
      latest_request: {
        review_request_id: "rev-req-002",
        reason: "Wrong-target reconciliation detected",
        requested_by: "harness",
        requested_at: "2024-01-17T10:35:00Z",
      },
      latest_decision: {
        review_id: "rev-dec-001",
        outcome: "rejected",
        notes: "Confirmed failure - Linear status was prematurely updated",
        reviewer: {
          reviewer_name: "alice.operator",
          reviewer_type: "human",
        },
        reviewed_at: "2024-01-17T11:00:00Z",
      },
      requests: [
        {
          review_request_id: "rev-req-002",
          reason: "Wrong-target reconciliation detected",
          requested_by: "harness",
          requested_at: "2024-01-17T10:35:00Z",
        },
      ],
      decisions: [
        {
          review_id: "rev-dec-001",
          outcome: "rejected",
          notes: "Confirmed failure - Linear status was prematurely updated",
          reviewer: {
            reviewer_name: "alice.operator",
            reviewer_type: "human",
          },
          reviewed_at: "2024-01-17T11:00:00Z",
        },
      ],
    },
    evaluation_summary: {
      count: 2,
      latest_action: "transition_applied",
      latest_recorded_at: "2024-01-17T11:00:00Z",
      latest_target_status: "failed",
    },
    timestamps: {
      created_at: "2024-01-17T08:00:00Z",
      updated_at: "2024-01-17T11:00:00Z",
      completed_at: null,
    },
    timeline: [
      {
        event_id: "TASK-004:created",
        event_type: "task_created",
        occurred_at: "2024-01-17T08:00:00Z",
        summary: "Task created",
        source: "manual",
        details: { status: "intake_ready" },
      },
      {
        event_id: "TASK-004:status:1",
        event_type: "status_transition",
        occurred_at: "2024-01-17T08:15:00Z",
        summary: "Status changed intake_ready -> assigned",
        source: "harness",
        details: { from_status: "intake_ready", to_status: "assigned" },
      },
      {
        event_id: "TASK-004:status:2",
        event_type: "status_transition",
        occurred_at: "2024-01-17T08:20:00Z",
        summary: "Status changed assigned -> executing",
        source: "harness",
        details: { from_status: "assigned", to_status: "executing" },
      },
      {
        event_id: "TASK-004:eval:1",
        event_type: "evaluation_recorded",
        occurred_at: "2024-01-17T10:30:00Z",
        summary: "Evaluation recorded: mark_failed",
        source: "harness",
        details: { action: "mark_failed", reasons: ["Executor timeout"] },
      },
      {
        event_id: "TASK-004:status:3",
        event_type: "status_transition",
        occurred_at: "2024-01-17T10:30:00Z",
        summary: "Status changed executing -> failed",
        source: "harness",
        details: { from_status: "executing", to_status: "failed" },
      },
      {
        event_id: "TASK-004:review:rev-req-002",
        event_type: "review_requested",
        occurred_at: "2024-01-17T10:35:00Z",
        summary: "Manual review requested",
        source: "harness",
        details: { reason: "Wrong-target reconciliation detected" },
      },
      {
        event_id: "TASK-004:review-dec:rev-dec-001",
        event_type: "review_decided",
        occurred_at: "2024-01-17T11:00:00Z",
        summary: "Manual review decided: rejected",
        source: "alice.operator",
        details: { outcome: "rejected" },
      },
    ],
    priority: "normal",
  },
  {
    task_id: "TASK-005",
    title: "Implement user settings page",
    description:
      "Create user settings page with profile editing, notification preferences, and account management.",
    current_status: "assigned",
    objective_summary: "User-facing settings interface",
    origin: {
      source_system: "linear",
      source_type: "ingress_request",
      source_id: "LIN-2860",
      ingress_id: "openclaw-003",
      ingress_name: "OpenClaw",
    },
    relationships: {
      parent_task_id: null,
      child_task_ids: [],
      dependencies: [{ task_id: "TASK-002", dependency_type: "blocks" }],
    },
    assigned_executor: {
      executor_type: "codex",
      executor_id: "codex-instance-delta",
      assignment_reason: "Frontend capability match",
    },
    evidence_summary: {
      artifact_count: 0,
      artifact_type_counts: {},
      verification_status_counts: {},
      validated_artifact_count: 0,
      completion_evidence: {
        policy: "artifact_backed",
        status: "awaiting",
        required_artifact_types: ["pull_request"],
        validated_artifact_ids: [],
        validation_method: null,
        validated_at: null,
      },
    },
    verification_summary: null,
    reconciliation_summary: null,
    review_summary: {
      status: "none",
      request_count: 0,
      decision_count: 0,
      latest_request: null,
      latest_decision: null,
      requests: [],
      decisions: [],
    },
    evaluation_summary: {
      count: 0,
      latest_action: null,
      latest_recorded_at: null,
      latest_target_status: null,
    },
    timestamps: {
      created_at: "2024-01-17T09:00:00Z",
      updated_at: "2024-01-17T09:30:00Z",
      completed_at: null,
    },
    timeline: [
      {
        event_id: "TASK-005:created",
        event_type: "task_created",
        occurred_at: "2024-01-17T09:00:00Z",
        summary: "Task created",
        source: "linear",
        details: { status: "intake_ready" },
      },
      {
        event_id: "TASK-005:status:1",
        event_type: "status_transition",
        occurred_at: "2024-01-17T09:30:00Z",
        summary: "Status changed intake_ready -> assigned",
        source: "harness",
        details: { from_status: "intake_ready", to_status: "assigned" },
      },
    ],
    priority: "normal",
  },
  {
    task_id: "TASK-006",
    title: "Add API rate limiting",
    description:
      "Implement rate limiting middleware for all public API endpoints with configurable thresholds.",
    current_status: "completed",
    objective_summary: "Rate-limited API endpoints",
    origin: {
      source_system: "linear",
      source_type: "ingress_request",
      source_id: "LIN-2845",
      ingress_id: "openclaw-001",
      ingress_name: "OpenClaw",
    },
    relationships: {
      parent_task_id: null,
      child_task_ids: [],
      dependencies: [],
    },
    assigned_executor: {
      executor_type: "codex",
      executor_id: "codex-instance-alpha",
      assignment_reason: "Backend capability match",
    },
    evidence_summary: {
      artifact_count: 2,
      artifact_type_counts: { pull_request: 1, commit: 1 },
      verification_status_counts: { verified: 2 },
      validated_artifact_count: 2,
      completion_evidence: {
        policy: "artifact_backed",
        status: "validated",
        required_artifact_types: ["pull_request"],
        validated_artifact_ids: ["art-030", "art-031"],
        validation_method: "automated",
        validated_at: "2024-01-13T16:00:00Z",
      },
    },
    verification_summary: {
      result: "accepted",
      completion_accepted: true,
      evidence_sufficient: true,
      reasons: ["PR merged", "Tests passing", "Documentation updated"],
      evaluated_at: "2024-01-13T16:00:00Z",
    },
    reconciliation_summary: {
      result: "no_mismatch",
      linear_state: "done",
      github_state: "merged",
      harness_state: "completed",
      mismatches: [],
      evaluated_at: "2024-01-13T16:05:00Z",
    },
    review_summary: {
      status: "none",
      request_count: 0,
      decision_count: 0,
      latest_request: null,
      latest_decision: null,
      requests: [],
      decisions: [],
    },
    evaluation_summary: {
      count: 1,
      latest_action: "transition_applied",
      latest_recorded_at: "2024-01-13T16:00:00Z",
      latest_target_status: "completed",
    },
    timestamps: {
      created_at: "2024-01-12T10:00:00Z",
      updated_at: "2024-01-13T16:05:00Z",
      completed_at: "2024-01-13T16:00:00Z",
    },
    timeline: [
      {
        event_id: "TASK-006:created",
        event_type: "task_created",
        occurred_at: "2024-01-12T10:00:00Z",
        summary: "Task created",
        source: "linear",
        details: { status: "intake_ready" },
      },
      {
        event_id: "TASK-006:status:1",
        event_type: "status_transition",
        occurred_at: "2024-01-12T10:30:00Z",
        summary: "Status changed intake_ready -> assigned",
        source: "harness",
        details: { from_status: "intake_ready", to_status: "assigned" },
      },
      {
        event_id: "TASK-006:artifact:art-030",
        event_type: "artifact_captured",
        occurred_at: "2024-01-13T14:00:00Z",
        summary: "Artifact captured: pull_request",
        source: "github",
        details: { type: "pull_request", pull_request_number: 138 },
      },
      {
        event_id: "TASK-006:eval:1",
        event_type: "evaluation_recorded",
        occurred_at: "2024-01-13T16:00:00Z",
        summary: "Evaluation recorded: accept_completion",
        source: "harness",
        details: { action: "accept_completion", accepted_completion: true },
      },
      {
        event_id: "TASK-006:status:2",
        event_type: "status_transition",
        occurred_at: "2024-01-13T16:00:00Z",
        summary: "Status changed executing -> completed",
        source: "harness",
        details: { from_status: "executing", to_status: "completed" },
      },
    ],
    priority: "high",
  },
];

// Helper to get a single task by ID
export function getTaskById(taskId: string): Task | undefined {
  return mockTasks.find((t) => t.task_id === taskId);
}

// Helper to filter tasks by status
export function getTasksByStatus(status: Task["current_status"]): Task[] {
  return mockTasks.filter((t) => t.current_status === status);
}

// Helper to get tasks requiring review
export function getTasksRequiringReview(): Task[] {
  return mockTasks.filter((t) => t.review_summary.status === "requested");
}
